from keyboards.client_kb import kb_client
from keyboards.client_kb import tools_inline_keyboard
from keyboards.client_kb import production_keyboard
from keyboards.client_kb import learning_inline_keyboard
from keyboards.client_kb import about_us_inline_keyboard
from keyboards.client_kb import question_about_us_inline_keyboard